name: 🛡️ ZUnit

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build-macos:
    name: 🧪 Mac ZUnit CI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: 📚 Molovo zunit
        run: |
          mkdir bin
          curl -fsSL https://raw.githubusercontent.com/zdharma/revolver/v0.2.4/revolver > bin/revolver
          curl -fsSL https://raw.githubusercontent.com/zdharma/color/d8f91ab5fcfceb623ae45d3333ad0e543775549c/color.zsh > bin/color
          curl -L https://raw.githubusercontent.com/zdharma/revolver/master/revolver > bin/revolver
          curl -L https://raw.githubusercontent.com/zdharma/color/master/color.zsh > bin/color
          git clone https://github.com/zdharma/zunit.git zunit.git
          cd zunit.git
          ./build.zsh
          cd ..
          mv ./zunit.git/zunit bin
          chmod u+x bin/{color,revolver,zunit}
      - name: ✏️ Run the test
        run: |
          export TERM="xterm-256color"
          export PATH="$PWD/bin:$PATH"
          zunit

  build-linux:
    name: 🧪 Linux Zunit CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: ℹ️ Setup linux dependencies
        run: |
          sudo apt update
          sudo apt-get install zsh -yq
      - name: 📚 Molovo zunit
        run: |
          mkdir bin
          curl -fsSL https://raw.githubusercontent.com/zdharma/revolver/v0.2.4/revolver > bin/revolver
          curl -fsSL https://raw.githubusercontent.com/zdharma/color/d8f91ab5fcfceb623ae45d3333ad0e543775549c/color.zsh > bin/color
          curl -L https://raw.githubusercontent.com/zdharma/revolver/master/revolver > bin/revolver
          curl -L https://raw.githubusercontent.com/zdharma/color/master/color.zsh > bin/color
          git clone https://github.com/zdharma/zunit.git zunit.git
          cd zunit.git
          ./build.zsh
          cd ..
          mv ./zunit.git/zunit bin
          chmod u+x bin/{color,revolver,zunit}
      - name: ✏️ Run the test
        run: |
          export TERM="xterm-256color"
          export PATH="$PWD/bin:$PATH"
          zunit
